backend:
  name: github
  branch: master
  repo: "roobottom/roobottom-2020"
  api_route: "https://api.github.com"
  site_domain: "cms.netlify.com"
  base_url: "https://api.netlify.com"
  auth_endpoint: "auth"
  cms_label_prefix: "netlify-cms/"
media_folder: "_source/images/photos"
public_folder: "/images/photos"
collections:
  - name: "photos"
    label: "Photos"
    folder: "_source/photos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: true
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "list"
        collapsed: false
        required: false
      - label: "Photos"
        name: "photo"
        widget: "list"
        collapsed: false
        label_singular: "photo"
        fields:
          - label: "File"
            name: "url"
            widget: "image"
          - label: "Description"
            name: "alt"
            widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false